Improvements

diff --git a/.github/workflows/crac-publish.yml b/.github/workflows/crac-publish.yml
--- a/.github/workflows/crac-publish.yml
+++ b/.github/workflows/crac-publish.yml
@@ -37,7 +37,12 @@ jobs:
       - run: |
          docker build . -t "ghcr.io/${{ github.repository }}:hello-world-crac-checkpointer" --file crac/Dockerfile
          CONTAINER_ID=$(docker run -d --cap-add CHECKPOINT_RESTORE --cap-add SYS_PTRACE --rm --name hello-world-crac-checkpointer "ghcr.io/${{ github.repository }}:hello-world-crac-checkpointer")
-         docker logs -f $CONTAINER_ID
+          
+          while logs=$(docker logs "$CONTAINER_ID" 2>&1); do
+            echo "$logs" | grep -q "Checkpoint creation succeeded" && echo "Checkpoint creation succeeded" && break
+            echo "$logs" | grep -q "Checkpoint creation failed" && echo "Checkpoint creation failed" && exit 1
+            sleep 2
+          done
           
          docker commit --change='ENTRYPOINT ["/opt/app/entrypoint.sh"]' $CONTAINER_ID "ghcr.io/${{ github.repository }}:hello-world-crac"
          docker kill $CONTAINER_ID
